version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
      - "80:3000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=sepia
      - DB_PASSWORD=password1234
      - DB_DATABASE=hackathon_platform
    command: sh -c "/wait-for postgres:5432 -- npm run start"
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    container_name: hackathon_db
    environment:
      POSTGRES_DB: hackathon_platform
      POSTGRES_USER: sepia
      POSTGRES_PASSWORD: password1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sepia -d hackathon_platform"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: